### ISSUE TITLE
 Failed to write provider heartbeat to redis registry. registry: 10.20.13.162:7001, cause: MOVED 6819 10.20.13.162:7000

### ISSUE THREAD

**Issue by li362692680** [apache/incubator-dubbo#1050]
使用redis 3.2集群作为注册中心时报
 Failed to write provider heartbeat to redis registry. registry: 10.20.13.162:7001, cause: MOVED 6819 10.20.13.162:7000

**Comment by chickenlj** [comment]
Do you use redis cluster? `MOVED 6819 ` is a typical error on redis cluster, please check if you have proper configuration on your redis cluster.

Also, redis registry based on a really old redis version that do not support cluster, so redis cluster has not been tested yet.

**Comment by beiwei30** [comment]
@li362692680 how do you configure redis cluster in your dubbo application?

**Comment by beiwei30** [comment]
I guess the root cause is your redis cluster is configured as a [real redis cluster](https://redis.io/topics/cluster-tutorial), but this mode doesn't support in dubbo, that is, replication is not controlled by redis cluster, but controlled by dubbo. 

Instead, you should setup your redis nodes as individual instances, and configure like this:

```xml
<dubbo:registry address="redis://10.20.153.10:6379?backup=10.20.153.11:6379,10.20.153.12:6379" />
```

or

```xml
<dubbo:registry protocol="redis" address="10.20.153.10:6379,10.20.153.11:6379,10.20.153.12:6379" />
```

Here's one good article to explain the different redis deployments: https://greatestrabit.github.io/2016/04/17/firstjedis/

**Comment by beiwei30** [comment]
I think the problem should no longer exist once you setup redis instances as I suggest.
