### ISSUE TITLE
Does Dubbo consider the support for the native Thrift protocol?

### ISSUE THREAD

**Issue by mawenjian** [apache/incubator-dubbo#1095]
我们在技术选型时很是纠结，用Dubbo吧，对其他语言的支持不太好；用Thrift吧，又没有完善的服务治理。虽然Dubbo支持Thrift协议，但是非原生的，跨语言的支持是个问题。虽然可以通过对Dubbo改造以支持原生Thrift协议，但是未经官方确认，不敢贸然在生产环境使用。

所以我想问下，在接下来的开发规划中，官方是否有考虑对原生Thrift协议的支持？

**Comment by www1350** [comment]
这个应该只要编码解码的时候弄下就行了

**Comment by chickenlj** [comment]
We are considering support the original ` Thrift RPC Protocol`, this can solve the communication problem when your need to program cross languages. But still, our service management ability only restricted to `java`, because we don't have multi-language implementations for dubbo core features. Maybe in the future, we will figure out a plan like Service Mesh to solve this problem.

**Comment by mawenjian** [comment]
Many thanks. I'm willing for the day that Dubbo supports the native `Thrift RPC Protocol`.

**Comment by chickenlj** [comment]
@lovepoem  is working on this feature.

**Comment by chickenlj** [comment]
Duplicate with #1559

**Comment by awayings** [comment]
thrift support attachemnts transfer?
