### ISSUE TITLE
how to dubbo-provider using host ip of docker container

### ISSUE THREAD

**Issue by ryankong** [apache/incubator-dubbo#1432]
when dubbo-provider run in docker container ,it rigistried by the ip of contaner ,which unvisitable by other server

**Comment by vangoleo** [comment]
You can add `--net=host` to docker run command, for example, `docker run --net=host dubbo-provider`.

**Comment by EdwardLee03** [comment]
So that can not deploy multiple dubbo apps on a docker, unless use different port. It is not recommended, suggest to use the virtual IP of docker.  @ryankong

**Comment by MouGG** [comment]
Hi, @vangoleo, thanks for your reply, what about running a dubbo-provider in a k8s cluster? As we konwn, dubbo register the podIP rather than a nodeIP to registry(zookeeper), thus consumer outside of k8s cluster cannot reach to the providers within k8s. Any solution to register nodeIP to ZK instead?

**Comment by ralf0131** [comment]
Please check this example: https://github.com/dubbo/dubbo-samples/tree/master/dubbo-samples-docker

**Comment by baozi-2019** [comment]
> Please check this example: https://github.com/dubbo/dubbo-samples/tree/master/dubbo-samples-docker

It is not found now.

**Comment by AlbumenJ** [comment]
@baozi-2019 Moved to https://github.com/apache/dubbo-samples/tree/master/2-advanced/dubbo-samples-docker
