### ISSUE TITLE
[BUG][2.5.10] Implementation-Version is incorrect

### ISSUE THREAD

**Issue by nobodyiam** [apache/incubator-dubbo#1466]
The manifest info of the newly released 2.5.10 is incorrect, which causes `com.alibaba.dubbo.common.Version#getVersion()` returns the wrong version - `2.0.1`.

The following is the manifest of 2.5.10:

```properties
Manifest-Version: 1.0
Implementation-Vendor: The Dubbo Project
Implementation-Title: Dubbo
Implementation-Version: 2.0.1
Implementation-Vendor-Id: com.alibaba
Built-By: ken.lj
Build-Jdk: 1.7.0_80
Specification-Vendor: The Dubbo Project
Specification-Title: Dubbo
Created-By: Apache Maven 3.1.1
Specification-Version: 2.0.0
Archiver-Version: Plexus Archiver
```

Here is the manifest of 2.5.8, which is correct:

```properties
Manifest-Version: 1.0
Implementation-Vendor: Alibaba
Implementation-Title: Dubbo
Implementation-Version: 2.5.8
Implementation-Vendor-Id: com.alibaba
Built-By: ken.lj
Build-Jdk: 1.6.0_32
Specification-Vendor: Alibaba
Specification-Title: Dubbo
Created-By: Apache Maven 3.1.1
Specification-Version: 2.5.8
Archiver-Version: Plexus Archiver
```

**Comment by chickenlj** [comment]
This has been changed since 2.5.9, does this change has some side effects on your project?

**Comment by nobodyiam** [comment]
We have integrated dubbo with our tracing system, which will include dubbo version in each rpc call event.

The version information is one of the key diagnosis information when some service meets something wrong.

So yes, this change does have some side effects. Not on my project but on many services using our sdk.

**Comment by chickenlj** [comment]
Hi Jun,

We have integrated dubbo with our tracing system, which will include dubbo version in each rpc call event.

The version information is one of the key diagnosis information when some service meets something wrong.

So yes, this change does have some side effects. Not on my project but on many services using our sdk.


Thanks!
Jason

**Comment by beiwei30** [comment]
Jason,

Pls. file an issue on github.

Thanks,
-Ian.

**Comment by kimmking** [comment]
i think 2.5.10 is better

**Comment by chickenlj** [comment]
Sorry for bothering you.

I have checked the design purpose and implementation code before made this change. I believe the `version` here means the implementation version of the RPC Protocol,  also the Protocol-Specific-Version means the specification of RPC Protocol. If i understand the `version` in a right way, don’t think it should be changed for every release(or at least don’t have to be the same with the jar version).

I know that there maybe some compatible problems if someone relies on this “version number the same with the jar version” rule, but this change should not cause any critical problems on remote procedures. I tend to do this when i have to do a compatible upgrade for RPC protocols, check this PR(https://github.com/alibaba/dubbo/pull/1442#issuecomment-371776703 <https://github.com/alibaba/dubbo/pull/1442#issuecomment-371776703>, not completely finished yet). I think it would be better for us to keep a stable version number instead of change every release.

Only my opinion. And I believe when we follow the apache way by using the dev mailing list - dev@dubbo.apache.org, we can avoid any changes before they are fully discussed.

**Comment by nobodyiam** [comment]
Thanks for the clarification, I'm OK with this for now.

However, I'm not sure whethere it's a good idea to bind `RPC protocol Version` to the `Specification-Version` in a Jar Manifest file. 

In my opinion, they are 2 different concepts. For example, one jar file could provide several different rpc protocols, in that case, we won't be able to use the `Specification-Version` in one Jar Manifest file to represent multiple `RPC protocol Versions`.

**Comment by chickenlj** [comment]
> However, I'm not sure whethere it's a good idea to bind RPC protocol Version to the Specification-Version in a Jar Manifest file.
> 
> In my opinion, they are 2 different concepts. For example, one jar file could provide several different rpc protocols, in that case, we won't be able to use the Specification-Version in one Jar Manifest file to represent multiple RPC protocol Versions
> 
Agree with you. Maybe we should figure out a new way for identifying RPC version, separate  RPC protocol Version from the Manifest specification/implementation version.

**Comment by lovepoem** [comment]
https://github.com/apache/incubator-dubbo/blob/master/dubbo-common/src/main/java/com/alibaba/dubbo/common/Version.java   

Version.java read version from MANIFEST.MF or jar name.

Now you debug in classes generated by IDE, no MANIFEST.MF or jar name found

Must we support the IDEA debug environment?

If so，we can refer this [Generate a Version.java file in Maven
](https://stackoverflow.com/questions/2469922/generate-a-version-java-file-in-maven)

**Comment by chickenlj** [comment]
#1843

**Comment by edwardlee03** [comment]
dubbo协议版本从`2.0.1`变更为`2.0.2`，原因原来是这个引起。

**Comment by qixiaobo** [comment]
We also meet the problem. This must mislead many developers. 
![image](https://user-images.githubusercontent.com/2881751/59838938-6a4d6780-9382-11e9-9577-101a7cd8c060.png)

**Comment by qixiaobo** [comment]
> We also meet the problem. This must mislead many developers.
> ![image](https://user-images.githubusercontent.com/2881751/59838938-6a4d6780-9382-11e9-9577-101a7cd8c060.png)
You can refer the code  here  
https://github.com/apache/dubbo/blame/2.6.x/dubbo-config/dubbo-config-api/src/main/java/com/alibaba/dubbo/config/ServiceConfig.java#L372
Acturally, we use the jar with version 2.6.6.
