### ISSUE TITLE
Where can I get the startup script for Dubbo

### ISSUE THREAD

**Issue by YFCoder2** [apache/incubator-dubbo#1548]
Where can I get the startup script for Dubbo like start.sh

**Comment by beiwei30** [comment]
There's no start.sh provided for dubbo application since the script varies depending on how you develop and deploy your dubbo provider/consumer. 

For the [demo](https://github.com/apache/incubator-dubbo/tree/master/dubbo-demo) we provide in dubbo project, you can either start it directly from your IDE or you can write the your own script similar like below if you prefer to start it from command line: 

```sh
java -classpath ${CLASSPATH} com.alibaba.dubbo.demo.consumer.Consumer
```
