### ISSUE TITLE
How long apache vesion

### ISSUE THREAD

**Issue by hadoop835** [apache/incubator-dubbo#1673]
How long apache vesion

**Comment by ralf0131** [comment]
Hi, we are planning to start the release process this week.

The discussion is happening in the mailing list, you can [subscribe](https://github.com/apache/incubator-dubbo/issues/1393) and get the latest updates there.

Since it is the first Apache release, it is expected to take 2~3 weeks.

Please also join the mailing list to vote for the release candidate, and we will announce it on the mailing list.
