### ISSUE TITLE
why parameter:send.reconnect default value is false?

### ISSUE THREAD

**Issue by zhaoyuguang** [apache/incubator-dubbo#1883]
why parameter:send.reconnect default value = false?
For what reason？

**Comment by carryxyh** [comment]
This param control a client do `connect()` when send a request.
The default ExchangeClient is HeaderExchangeClient which doesn't need to connect when send request, so the default SEND_RECONNECT_KEY is `false` to match the HeaderExchangeClient.

If u choose LazyConnectExchangeClient, the constructor like:
`this.url = url.addParameter(Constants.SEND_RECONNECT_KEY, Boolean.TRUE.toString());`
The SEND_RECONNECT_KEY is always true because LazyConnectExchangeClient will init client and connect to server when send request.

&READY-TO-CLOSE&
