### ISSUE TITLE
dubbo官网文档的问题

### ISSUE THREAD

**Issue by yjx1045072812** [apache/incubator-dubbo#1984]
关于本地存根的使用，文档上有这样一段demo：
![image](https://user-images.githubusercontent.com/35123083/41847036-42d9c704-78ab-11e8-95a2-abf63be62622.png)
但是我再实际使用dubbo的过程中发现，将provider端的stub开启后，实际上是在provider端执行stub，并非是在客户端上执行。如果想要在客户端执行stub，需要在客户端开启stub。
这样一来，文档上的说明就有误导性了，或者说是我使用的方式不对？

**Comment by chickenlj** [comment]
Docs: http://dubbo.apache.org/#!/docs/user/demos/local-stub.md?lang=zh-cn
Demo: https://github.com/dubbo/dubbo-samples/tree/master/dubbo-samples-stub

**Comment by sarins** [comment]
几个意思？ 意思是没有客户端存根吗？那这玩意有个毛用啊。码流都发到服务端了。

**Comment by diecui1202** [comment]
@sarins you could check this sample: https://github.com/dubbo/dubbo-samples/tree/master/dubbo-samples-stub

Stub is provided by provider side, but it is executed in consumer side.

**Comment by sarins** [comment]
@diecui1202 I had checkout the document and related source codes, which are looks like no match, I can NOT find out where is used to instantiate the service stub in the source code, it ONLY checkout the service stub class existable if you have config for you will use the stub(based on 2.6.4).

**Comment by diecui1202** [comment]
https://github.com/apache/incubator-dubbo/blob/dba175aecd02d9916b55570b59f6ef2e9c11ce32/dubbo-rpc/dubbo-rpc-api/src/main/java/org/apache/dubbo/rpc/proxy/wrapper/StubProxyFactoryWrapper.java#L84

@sarins set a breakpoint on DemoServiceStub constructor, and debug StubConsumer main class, you will get the right position instantiating stub instance.

![image](https://user-images.githubusercontent.com/1152291/47690618-b13af100-dc29-11e8-8935-963898dbc23e.png)

**Comment by diecui1202** [comment]
feel free to reopen if necessary.

**Comment by sarins** [comment]
I have try to generate stub classes dynamically on the consumer side by javassist, and look like below code clips, because most of RPC invocation scenes in same way in our project, but it did not work. I don't know why? 
![image](https://user-images.githubusercontent.com/1165129/47710514-e2d5ab80-dc6d-11e8-97e5-c7269e3f83e8.png)

![image](https://user-images.githubusercontent.com/1165129/47710409-b28e0d00-dc6d-11e8-8f27-54d0e2d44f79.png)
@diecui1202 actually, I think dynamically generate in the consumer side is equal effect with hard code in the provider side, right? but it did not work.

**Comment by sarins** [comment]
@diecui1202 do you mean the stub config should be in the provider side? thanks a lot.
