### ISSUE TITLE
Proposal for deprecated o.a.d.c.extension.Activate#before and #after

### ISSUE THREAD

**Issue by diecui1202** [apache/incubator-dubbo#2180]
I've checked the whole source code, these two methods haven't be used. Instead, #order is used more frequent.

More important, use these two properties for sorting is not correct. There has a issue and PR about it. See https://github.com/apache/incubator-dubbo/issues/1926 and https://github.com/apache/incubator-dubbo/pull/639

So, I suggest deprecating these two method on annotation Activate.

**Comment by kimmking** [comment]
+1 
and I think vote should be via email？

**Comment by diecui1202** [comment]
I'll send a PR to deprecate these two methods.

**Comment by cdfive** [comment]
@diecui1202 
Hi, I found the ActivateComparator class use these two methods, and there is also a test case: 
https://github.com/apache/incubator-dubbo/blob/master/dubbo-common/src/test/java/org/apache/dubbo/common/extension/support/ActivateComparatorTest.java
The test case use before and after method in filter's @Activate， and the case is passed.

#1926 is confusing, since I tried the before,after in our project, found it works. 

Consider a scene: a user's custorm filter which need to after or before a given filter, as the other filter's order are uncertain, the relative order maybe more more suitable.
