### ISSUE TITLE
UT failed on windows, IOUtilsTest#testWriteLines

### ISSUE THREAD

**Issue by playaround88** [apache/incubator-dubbo#2472]
- [*] I have searched the [issues](https://github.com/apache/incubator-dubbo/issues) of this repository and believe that this is not a duplicate.
- [*] I have checked the [FAQ](https://github.com/apache/incubator-dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.6.3-release
* Operating System version: windows 10
* Java version: JDK 1.8

### Step to reproduce this issue

1. mvn clean install -e

Pls. provide [GitHub address] to reproduce this issue.

### Expected Result

What do you expected from the above steps？
UT pass

### Actual Result

What is actually happen?
dubbo-common IOUtilsTest#testWriteLines assert error

If there is an exception, please attach the exception trace:

```
expect "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz1234567890\r"
actually "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz1234567890\r\n"
```

**Comment by playaround88** [comment]
Change
```java
    @Test
    public void testWriteLines() throws Exception {
        IOUtils.writeLines(os, new String[]{TEXT});
        ByteArrayOutputStream bos = (ByteArrayOutputStream) os;
        assertThat(new String(bos.toByteArray()), equalTo(TEXT + "\r"));
    }
```
To
```java
    @Test
    public void testWriteLines() throws Exception {
        IOUtils.writeLines(os, new String[]{TEXT});
        ByteArrayOutputStream bos = (ByteArrayOutputStream) os;
        assertThat(new String(bos.toByteArray()), equalTo(TEXT + System.lineSeparator()));
    }
```

**Comment by playaround88** [comment]
sorry, have be solved!

**Comment by GuldanChen** [comment]
are you kidding me？




    



    
    
    



    
        
            
                
                    
                        
                    
                    
                        
                            陈大清
                            
                            
                                
                                    邮箱：mccrea.jsk@gmail.com
                                
                        
                    
                
            
        
    


签名由 网易邮箱大师 定制


On 09/08/2018 20:59, wtb wrote: sorry, have be solved!

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/apache/incubator-dubbo","title":"apache/incubator-dubbo","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/apache/incubator-dubbo"}},"updates":{"snippets":[{"icon":"PERSON","message":"@playaround88 in #2472: sorry, have be solved!"}],"action":{"name":"View Issue","url":"https://github.com/apache/incubator-dubbo/issues/2472#issuecomment-419640299"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/apache/incubator-dubbo/issues/2472#issuecomment-419640299",
"url": "https://github.com/apache/incubator-dubbo/issues/2472#issuecomment-419640299",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [apache/incubator-dubbo] UT failed on windows, IOUtilsTest#testWriteLines (#2472)",
"sections": [
{
"text": "",
"activityTitle": "**wtb**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@playaround88",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"apache/incubator-dubbo\",\n\"issueId\": 2472,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/apache/incubator-dubbo/issues/2472#issuecomment-419640299"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 377449976\n}"
}
],
"themeColor": "26292E"
}
]
