### ISSUE TITLE
dubbo的exporterListener扩展有问题

### ISSUE THREAD

**Issue by kinglcc** [apache/incubator-dubbo#284]
AbstractServiceConfig继承自AbstractInterfaceConfig

AbstractServiceConfig有如下方法：

```
    @Parameter(key = Constants.EXPORTER_LISTENER_KEY, append = true)
    public String getListener() {
        return super.getListener();
    }

    @Override
    public void setListener(String listener) {
        checkMultiExtension(ExporterListener.class, "listener", listener);
        super.setListener(listener);
    }
```

AbstractInterfaceConfig中则是这样的：

```
    @Parameter(key = Constants.INVOKER_LISTENER_KEY, append = true)
    public String getListener() {
        checkMultiExtension(InvokerListener.class, "listener", listener);
        return listener;
    }
    public void setListener(String listener) {
        this.listener = listener;
    }
```

这么写的问题是当在@Service注解中指定listener时，set的时候是检查是否是ExporterListener，get的时候检查的则变成了InvokerListener。
当我只扩展了ExporterListener，而没有对应名字的InvokerListener的时候，dubbo会抛出异常：

```
Caused by: java.lang.IllegalStateException: No such extension xxxxx for listener/com.alibaba.dubbo.rpc.InvokerListener
    at com.alibaba.dubbo.config.AbstractConfig.checkMultiExtension(AbstractConfig.java:383) ~[dubbo-2.5.4-SNAPSHOT.jar:2.5.4-SNAPSHOT]
    at com.alibaba.dubbo.config.AbstractInterfaceConfig.getListener(AbstractInterfaceConfig.java:407) ~[dubbo-2.5.4-SNAPSHOT.jar:2.5.4-SNAPSHOT]
    at com.alibaba.dubbo.config.AbstractServiceConfig.getListener(AbstractServiceConfig.java:205) ~[dubbo-2.5.4-SNAPSHOT.jar:2.5.4-SNAPSHOT]
    ... 25 common frames omitted
```

**Comment by sxshunrj** [comment]
我也遇到了这个问题，请问最后是怎么解决的呢？

**Comment by ralf0131** [comment]
Hi, I have checke the latest code, 

AbstractServiceConfig#getListener() has been changed to:

```java
    @Parameter(key = Constants.EXPORTER_LISTENER_KEY, append = true)
    public String getListener() {
        return this.listener;
    }

    @Override
    public void setListener(String listener) {
        checkMultiExtension(ExporterListener.class, "listener", listener);
        super.setListener(listener);
    }
```

So this is not an issue anymore.

**Comment by linghushaoxia** [comment]
If it is not convenient to upgrade the version, you can't use the latest code. According to the bug of its code, you can "bug the bug"
According to the dev documentation, in the MET-INF folder, after the value of META-INF/dubbo/com.alibaba.dubbo.rpc.ExporterListener is xxx=com.xxx.XxxExporterListener, the startup will throw a mistake and cannot be started.
According to the code bug, the problem is the problem posted by @kinglcc. The reason for the error is that there is no InvokerListener, then the processing method is as follows
1. The current XxxExporterListener implements the InvokerListener interface at the same time, and the method implementation of the InvokerListener is left blank.
2. META-INF/dubbo/com.alibaba.dubbo.rpc.InvokerListener, the value is xxx=com.xxx.XxxExporterListener
This way, you can use the convenience of the ExporterListener without upgrading the framework. 

如果不方便升级版本，无法使用最新的代码，根据它的代码的bug，可以 "将bug就bug“
在按照dev文档，在MET-INF文件夹内配置好，META-INF/dubbo/com.alibaba.dubbo.rpc.ExporterListener的值为xxx=com.xxx.XxxExporterListener之后，启动会抛错，无法启动。
根据代码bug来看，问题就是 @kinglcc 贴出的问题。错误原因是，不存在InvokerListener，那么处理方法如下
1. 当前的XxxExporterListener同时实现InvokerListener接口，InvokerListener的方法实现留空。
2. META-INF/dubbo/com.alibaba.dubbo.rpc.InvokerListener，值为xxx=com.xxx.XxxExporterListener
这样子，就可以在不升级框架的情况下，来使用ExporterListener带来的便利。

**Comment by whx5572371** [comment]
> Hi, I have checke the latest code,
> 
> AbstractServiceConfig#getListener() has been changed to:
> 
> ```java
>     @Parameter(key = Constants.EXPORTER_LISTENER_KEY, append = true)
>     public String getListener() {
>         return this.listener;
>     }
> 
>     @Override
>     public void setListener(String listener) {
>         checkMultiExtension(ExporterListener.class, "listener", listener);
>         super.setListener(listener);
>     }
> ```
> 
> So this is not an issue anymore.
你确定么?现在是2019年了 master版本和你说的不一样啊. 还有别人用中文问问题,你为什么用英文回答呢??
