### ISSUE TITLE
What's the difference between ConfigUtils with ConfigurationUtils？

### ISSUE THREAD

**Issue by Bricks-Man** [apache/incubator-dubbo#3379]
- [x] I have searched the [issues](https://github.com/apache/incubator-dubbo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/apache/incubator-dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: master
* Operating System version: deepin
* Java version: 1.8

What's the difference between ConfigUtils with ConfigurationUtils？
I found in dubbo-container module,log4j and spring submodule use different config util class to get property.Is there any difference between the two?

**Comment by chickenlj** [comment]
> What's the difference between ConfigUtils with ConfigurationUtils？

ConfigUtils serves only for the reading of local `.properties` file, such as `dubbo.properties` in your classpath. It's legacy from 2.6.x.

ConfigurationUtils is newly introduced in 2.7.0, it reads properties from CompositeConfiguration 
 while ConfigUtils is included only as one property source of  sources, for example

You should use `ConfigutionUtils` instead of `ConfigUtils` start from 2.7.0. I admit that it's to some extent confusing, we'll see how to better distinguish these two classes next.

**Comment by Jeff-Lv** [comment]
me too confusion for those two class name. I think we'd better add a deprecated annotation to configUtils or rename it to LocalPropertiesUtil like that.
