### ISSUE TITLE
async call not work when use zipkin

### ISSUE THREAD

**Issue by maxiaoguang64** [apache/incubator-dubbo#3576]
dubbo version 2.6.x
zipkin plugin version 5.6.1

![y1 r08 0hw fm c py 4kj](https://user-images.githubusercontent.com/6637227/53537044-929b2700-3b43-11e9-80a0-0f7ad8f58e90.png)

result.hasException() will call future.get() to wait result

**Comment by maxiaoguang64** [comment]
@chickenlj   can we disscus this

**Comment by chickenlj** [comment]
> result.hasException() will call future.get() to wait result

Sorry, but I don't understand why `result.hasException` will trigger future.get().

Can you provide the complete code implementation which the above snippet belongs to?

**Comment by maxiaoguang64** [comment]
@chickenlj 
i am sorry, i use dubbo 2.7.0-SNAPSHOT.
![image](https://user-images.githubusercontent.com/6637227/53781255-0faf0d80-3f43-11e9-84f1-be8c1c0a9556.png)
but 2.7.0-RELEASE already fix it.
![image](https://user-images.githubusercontent.com/6637227/53781278-29505500-3f43-11e9-90ad-95c3be4fe430.png)


![image](https://user-images.githubusercontent.com/6637227/53781460-e2af2a80-3f43-11e9-9712-8a93fb707d91.png)
Is this necessary?
oneway and async are difference.
![image](https://user-images.githubusercontent.com/6637227/53782494-77b42280-3f48-11e9-94c0-b84eea6ce135.png)
![image](https://user-images.githubusercontent.com/6637227/53782528-9b776880-3f48-11e9-85b2-27d6a5267987.png)
call tracing   consumer--->provider1--->provider2
use async call
but i can't wait result.

**Comment by maxiaoguang64** [comment]
@chickenlj  can i do something?

**Comment by chickenlj** [comment]
> but 2.7.0-RELEASE already fix it.

Yes, the bug you reported will be fixed in 2.7.1 release.


![img](https://user-images.githubusercontent.com/6637227/53781460-e2af2a80-3f43-11e9-9712-8a93fb707d91.png)
> Is this necessary?

You can use `RpcContext.getCompletableFuture()` and add callback to CompletableFuture directly.
And I would recommend you record the Finish Span in `Filter.onResponse`, it works for both sync and async scenario, you do not need to register any callback. Whenever `onResponse` is called, indicates the actual result returns.
